version: "3.9"

services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9090
    command: >
      /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf &&
      nginx -g 'daemon off;'"
    ports:
      - 8081:80
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9090
    volumes:
      - ./flask:/src
    depends_on:
      - mongo

  mongo:
    image: mongo
