apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
    - name: test
      image: docker.io/rkalluru/centos-sleep
      env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: demo-cm
              key: URL
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: USERNAME
      volumeMounts:
        - name: my-storage
          mountPath: /mnt/data
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: ebs-claim
