apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-cm
data:
  URL: yahoo.com
  DB_HOST: xyz.com

---

apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
data:
  USERNAME: YWRtaW4=        # admin
  PASSWORD: QWRtaW4xMjM=    # Admin123


---

apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
  - name: test
    image: docker.io/rkalluru/centos-sleep
    env:
    - name: URL
      valueFrom:
        configMapKeyRef:
          name: demo-cm
          key: URL

    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: demo-secret
          key: USERNAME
volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: ebs-claim      # your PVC name
