apiVersion: v1
kind: Namespace
metadata:
  name: tcs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goverdhan-deployment
  namespace: tcs
  labels:
    app: indianflag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: indianflag
  template:
    metadata:
      labels:
        app: indianflag
    spec:
      containers:
        - name: indianflag
          image: goverdhannaidu/indianflag:v1
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: indianflag-service
  namespace: tcs
spec:
  type: LoadBalancer
  selector:
    app: indianflag
  ports:
    - port: 80
      targetPort: 80
